language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install
services:
- postgresql
env:
  global:
  - NODE_ENV=test
  - secure: DYcb7tIFFF1oAyAsz2oOuY2Dfx6nTASJFilfZydSPFvb0p8MuqGLGtSEBsYoumov5Vvy/nQGURnpofR+cf/5oHYYIS1Ul3Dne4prqsZ/i+hsZ5NDIT1VedaOQ0xYBbDI33V9phoe7pohvUFGrD7x/rw50ntP+DPp8Ow384cKznkzeiFsY4PoWtBMUziX/NUgWJm7hUT853snj+OLsrMIQGqjHFIcGhrbaevrmV4lE9XkQFjxfgOBtzOaY5EGDoSbRKcB3jp15q+7THOyVqSGUIxjmG6QGyhB59u0TYDIoOhL5GsanfGUHXO+uErypWbGRLs74r+lORpRHSX3f8HfrJtRYUAJJOm0UjsBMuzbXmmUZHWSiW805cgOy9cg1P1L3s7dUUGuNtyXcgUIa2hr41iXI369c+Gyhw41F8qvoJaeZgGB7ezvd5E5DnqDVra2HbtKRyBOJo1bHZdh95yyN8L1lzWlKOuxRzetVWUf/IQho6ibnA0r4dVRziRja67um3iFWCatR4tr9UYC2xXPo7bA+giQuMutZvIR8P0uuyGEaA5rdKw+kCKeAqxMhJeaivBPVVryEuxeots2SqMW+rkBhWrPT+NLFaDdcDSphhQyKt/jsmDxapB5a6NTowI9VqwncKZpAL91+tNYvsUOfGOYXmpX+RYuNSdpoQ5Ta6g=
before_script:
- psql -c 'create database book_test;' -U postgres
- npm run build
- npm install -g sequelize-cli
- sequelize db:migrate
script:
- npm test
after_success:
- npm run coverage
before_deploy:
- npm install now --no-save
- now rm node-cd --token $NOW_TOKEN --yes || true
deploy:
- provider: script
  script: now --public --token $NOW_TOKEN
  skip_cleanup: true
  on:
    master: true
    develop: true
